services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile.prod
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      retries: 5
    environment:
      - NODE_ENV=production




