sonar.projectKey=hugo-canovas_devops
sonar.organization=HugoCanovas

sonar.sources=app

sonar.exclusions=node_modules/**,.next/**,public/**,tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info